# Generated by Django 3.2.23 on 2024-02-13 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("home", "0001_load_initial_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ihjvbf",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vcbcc", models.BigIntegerField()),
                ("reyeue", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Gbcmcm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vcbdb", models.BigIntegerField()),
                ("reyey", models.BigIntegerField()),
                (
                    "rel_ihjvbf_1_1",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gbcmcm_rel_ihjvbf_1_1",
                        to="home.ihjvbf",
                    ),
                ),
            ],
        ),
    ]
